server:
  port: 8082

spring:
  datasource:
   driver-class-name: org.postgresql.Driver
   url: jdbc:postgresql://${POSTGRES_HOSTNAME:localhost}:${POSTGRES_PORT:15432}/${POSTGRES_DB:postgres}
   username: ${POSTGRES_USER:postgres}
   password: ${POSTGRES_PASSWORD:postgres}
  kafka:
    bootstrap-servers: ${KAFKA_ADVERTISED_LISTENERS:http://localhost:9094}



logging:
  level:
    io.kafka: DEBUG


