version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 15432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      zkh-network:
        ipv4_address: 172.19.0.2

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"
    networks:
      zkh-network:
        ipv4_address: 172.19.0.7

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
      - zookeeper
    ports:
      - "9094:9094"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://172.19.0.8:9093,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://172.19.0.8:9093,OUTSIDE://0.0.0.0:9094
      KAFKA_ZOOKEEPER_CONNECT: 172.19.0.7:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    networks:
      zkh-network:
        ipv4_address: 172.19.0.8


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "11111111!"
    ports:
      - "16543:80"
    networks:
      zkh-network:
        ipv4_address: 172.19.0.10


#networks
networks:
  zkh-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16

volumes:
  postgres_data:
